/*
 * generated by Xtext
 */
package xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XModifUiModule extends xtext.ui.AbstractXModifUiModule {
	public XModifUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator(){
		return XModifHighlightingSemanticCalculator.class;
	}

	public Class<XModifHighlightingConfiguration> bindIHighlightingConfiguration() {
		return XModifHighlightingConfiguration.class;
	}
	

}
