<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="imoca" nsURI="http://fr.ubo.mde.goulven.imoca" nsPrefix="imoca">
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="theController" lowerBound="1"
        eType="#//ControllerContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ios" upperBound="-1" eType="#//IO"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adapters" upperBound="-1"
        eType="#//Adapter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//Data"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modes" upperBound="-1"
        eType="#//Mode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" upperBound="-1"
        eType="#//ControlConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControllableElement" abstract="true"
      eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isControllable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Periodic" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameterized" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byDefaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimalBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximalBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isModifiable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IO" abstract="true" eSuperTypes="#//NamedElement #//Parameterized">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//IO #//Periodic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adapters" upperBound="-1"
        eType="#//AdapterSI" eOpposite="#//AdapterSI/sensors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//IO #//Periodic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adapters" upperBound="-1"
        eType="#//AdapterOA" eOpposite="#//AdapterOA/actuators"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
        eType="#//Control" eOpposite="#//Control/inputs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adapter" eType="#//AdapterSI"
        eOpposite="#//AdapterSI/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
        eType="#//Control" eOpposite="#//Control/output"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adapter" eType="#//AdapterOA"
        eOpposite="#//AdapterOA/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adapter" abstract="true" eSuperTypes="#//NamedElement #//Parameterized"/>
  <eClassifiers xsi:type="ecore:EClass" name="AdapterSI" eSuperTypes="#//Adapter #//Periodic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensors" lowerBound="1"
        upperBound="-1" eType="#//Sensor" eOpposite="#//Sensor/adapters"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" eType="#//Input"
        eOpposite="#//Input/adapter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdapterOA" eSuperTypes="#//Adapter #//Periodic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="#//Output" eOpposite="#//Output/adapter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actuators" lowerBound="1"
        upperBound="-1" eType="#//Actuator" eOpposite="#//Actuator/adapters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="byDefaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumeratedData" abstract="true" eSuperTypes="#//Data">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContinuousData" abstract="true" eSuperTypes="#//Data">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimalBound" lowerBound="1"

        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximalBound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumeratedInput" eSuperTypes="#//EnumeratedData #//Input"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContinuousInput" eSuperTypes="#//ContinuousData #//Input"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumeratedCommand" eSuperTypes="#//EnumeratedData #//Output"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContinuousCommand" eSuperTypes="#//ContinuousData #//Output"/>
  <eClassifiers xsi:type="ecore:EClass" name="ControllerContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reactiveController" lowerBound="1"
        eType="#//ReactiveController" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expertController" lowerBound="1"
        eType="#//ExpertController" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaptativeController" lowerBound="1"
        eType="#//AdaptativeController" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdaptativeController" eSuperTypes="#//Periodic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adaptations" upperBound="-1"
        eType="#//Adaptation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="byDefault" lowerBound="1"
        eType="#//Adaptation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adaptation" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//Context" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" lowerBound="1"
        upperBound="-1" eType="#//ControlConfiguration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="observedData" upperBound="-1"
        eType="#//Input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlConfiguration" eSuperTypes="#//ControllableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ParameterDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="#//Control"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpertController" eSuperTypes="#//Periodic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="byDefaultMode" lowerBound="1"
        eType="#//Mode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mode" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" lowerBound="1"
        eType="#//Control"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setPoints" upperBound="-1"
        eType="#//SetPoint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="observedData" lowerBound="1"
        eType="#//Input"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" lowerBound="1"
        eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Mode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Mode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReactiveController">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentMode" lowerBound="1"
        eType="#//Mode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentConfiguration" eType="#//ControlConfiguration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1"
        eType="#//Control" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Control" abstract="true" eSuperTypes="#//NamedElement #//Parameterized #//Periodic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Input" eOpposite="#//Input/controls"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        upperBound="-1" eType="#//Output" eOpposite="#//Output/controls"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PID" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EReference" name="P" upperBound="-1" eType="#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="I" upperBound="-1" eType="#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="D" upperBound="-1" eType="#//Parameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpaqueControl" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetPoint" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//Data"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="float"/>
    <eLiterals name="double" value="1"/>
    <eLiterals name="int" value="2"/>
    <eLiterals name="boolean" value="3"/>
    <eLiterals name="byte" value="6"/>
    <eLiterals name="char" value="4"/>
    <eLiterals name="string" value="5"/>
  </eClassifiers>
</ecore:EPackage>
