<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modelegraphe" nsURI="http://mde.vallejo.modelegraphe" nsPrefix="mde.vallejo.modelegraphe">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Graphe" eSuperTypes="#//ElementNomme">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listeNoeuds" upperBound="-1"
        eType="#//Noeud" containment="true" eOpposite="#//Noeud/graphe"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listeArcs" upperBound="-1"
        eType="#//Arc" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Noeud" eSuperTypes="#//ElementNomme">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="toManyOutput"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="toManyOutput" value="&#xA;&#x9;&#x9;&#x9;graphe.listeArcs->select(origine=self)->size()&lt;=2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graphe" lowerBound="1"
        eType="#//Graphe" eOpposite="#//Graphe/listeNoeuds"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arc" eSuperTypes="#//ElementNomme">
    <eStructuralFeatures xsi:type="ecore:EReference" name="origine" lowerBound="1"
        eType="#//Noeud"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extremite" lowerBound="1"
        eType="#//Noeud"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementNomme" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
